docs: add roadmap in readme
kataw/kataw pull request #136
Opened 2021-06-22 13:55 UTC by aladdin-add

refs: https://github.com/kataw/kataw/discussions/128

2021-06-22 18:28 UTC, KFlash commented
LGTM. But move the Roadmap to end of the readme.

2021-06-22 18:55 UTC, KFlash commented
I will fix v. 0.1, but I let you handle the bullet points for v. 0.2 👍

2021-06-22 19:29 UTC, KFlash commented on README.md
> +## 📌v0.1 roadmap
Move to the bottom of the file

2021-06-22 19:29 UTC, KFlash requested changes
Move to bottom of the readme, not at the top.

2021-06-25 12:14 UTC, KFlash commented
@aladdin-add friendly ping

2021-06-30 13:48 UTC, KFlash commented
@aladdin-add friendly ping

2021-07-08 06:43 UTC, KFlash commented
@aladdin-add I think the readme in this PR is kind of messed up ;)

2021-07-08 06:52 UTC, aladdin-add commented
missing a blank line before the toc, should be addressed now. :)

2021-07-08 07:14 UTC, KFlash commented
Shouldn't be added **after** the intro text? Makes it more readable.

And missing a section about printing

2021-07-08 07:29 UTC, aladdin-add commented
> Shouldn't be added after the intro text? Makes it more readable.

yes, it should be. but the intro is a bit too long. it makes sense the toc be in the first page. thoughts?

2021-07-08 07:49 UTC, KFlash commented
You either split up the intro or rewrite it and then merge.  Everything is fine.

2021-07-08 07:54 UTC, KFlash commented
I still think you need to adjust the readme. Now at the top 'kataw' is used 3x. Should reduce to 1.

2021-07-08 07:54 UTC, KFlash commented
I still think you need to adjust the readme. Now at the top 'kataw' is used 3x. Should reduce to 1.

2021-07-08 07:55 UTC, KFlash approved these changes

2021-07-08 07:55 UTC, KFlash approved these changes

2021-07-08 08:34 UTC, merged